# Generated by Django 6.0.3 on 2026-03-09 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowify', '0002_discounttag_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='featuredoffer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glowify.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='glowify.product'),
        ),
    ]
